curl chrome impersonation bionic build errors HELP wanted do not merge .not ready yet.
 if anyone is not tired of bionic already here are some
errors -fno-exceptions should have removed the first ones.

I am going to work on a stand alone glibc repo instead and try to make
my default shell GNU I have just about had it with this maybe someone
can encourage me to explain why we need bionic at all I never use th
graphics card or system drivers anyway . or hardly ever

pip install curl_cffi for bionic is missing this lib because no one no
same person could build it in bionic

~~~sh

termux - building curl-impersonate for arch aarch64...
[1/1] Linking C executable src/curl
FAILED: src/curl
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: __cxa_begin_catch
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: std::terminate()
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: __gxx_personality_v0
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: __cxa_rethrow
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: __cxa_end_catch
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: void std::__ndk1::__sort<std::__ndk1::__less<unsigned short, unsigned short>&, unsigned short*>(unsigned short*, unsigned short*, std::__ndk1::__less<unsigned short, unsigned short>&)
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: operator delete(void*)
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: vtable for __cxxabiv1::__class_type_info
>>> referenced by lib/libcurl.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: vtable for __cxxabiv1::__si_class_type_info
>>> referenced by lib/libcurl.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.