remove vkmark
This fixes

ERROR: Duplicated package: vkmark
ERROR: Obtaining buildorder failed

... on CI.

The problem is because vkmark package already exist in termux repo.
So removing it from tur seems plausible.
Fixes https://github.com/termux-user-repository/tur/issues/1445