tree-wide: port debpython to TUR
- https://github.com/termux/termux-packages/pull/23652 for TUR

- Fix builds of all TUR Python packages

- Newer version of `maturin` requires adjustments to `ANDROID_API_LEVEL` and `wheel_arch` variables to build successfully

- `dlib` had a fatal build error related to `libjpeg`, so unvendored all dependencies at the same time as fixing the `libjpeg` error

- Switch `python-scipy` from PyPi `pybind11` to Termux `pybind11` to prevent `/usr/include/python3.12/pyconfig.h:17:12: fatal error: arm-linux-gnueabi/python3.12/pyconfig.h: No such file or directory`